### PR TITLE
Check for nodejs version

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Review by asamuzaK — CHANGES_REQUESTED** [review]
* Use double quotes for strings.
* `version` instead of `versions` will do.
* Use deconstruct instead of array[0]
  ```
   let [nodeMajor] = version.split(".");
   nodeMajor *= 1;
   if (Number.isInteger(nodeMajor) && nodeMajor < 8) {
   }
   ```

**Comment by asamuzaK** [comment]
BTW, is this really needed?
If node < 8, it will throw SyntaxError anyway.

**Comment by DamienCassou** [comment]
> Use double quotes for strings.

done. What about adding eslint to let travis detect that kind of error? I can send a PR if you agree.

> `version` instead of `versions` will do

I didn't do that because `version` has a `"v"` prefix. I can do it if you insist (but please tell me why you prefer it in this case).

```
> process.version
'v8.1.4'
> process.versions.node
'8.1.4'
```

> `nodeMajor *= 1;`

done, but I usually prefer being explicit about the intent of the code I write (I follow the "reveal intention" best practice pattern). If you don't mind, I would prefer `Number(nodeMajor)`.

> BTW, is this really needed? If node < 8, it will throw SyntaxError anyway.

I think it makes things clearer for the user. With this error message, the user will know he needs to update and won't blame you for writing non-working code.

**Comment by asamuzaK** [comment]
> What about adding eslint to let travis detect that kind of error? I can send a PR if you agree.

Thanks, please.
I have .eslintrc which I use.

> I didn't do that because version has a "v" prefix.

Oh, I missed that.
Then how about
```
const {versions: {node}} = require("process");
```

> If you don't mind, I would prefer Number(nodeMajor).

OK.

> I think it makes things clearer for the user.

user === developer, right?
I'm not against this PR, but it seems to me that he/she should at least look into package.json before installing anything.

I mean isn't it better to add this kind of check in their own repository than in this helper module?

**Comment by asamuzaK** [comment]
Oh, I found my mistake.
```
if (!Number.isInteger(nodeMajor) || nodeMajor < 8) {
}
```

**Comment by DamienCassou** [comment]
I fixed the PR based on your feedback.

> I have .eslintrc which I use

can you please send it to me in an email so I can setup everything the way you want?

> `const {versions: {node}} = require("process");`

I changed that but I'm not sure it helps code reading. Now, the variable is called `node` and the reader has no clue that it is a version number.

> user === developer, right?

Not necessarily. It can also be a user of the add-on who needs to install the native application (e.g., through [setup.js](https://github.com/asamuzaK/withExEditorHost/blob/master/setup.js)).

> `if (!Number.isInteger(nodeMajor) || nodeMajor < 8) {`

I also found your first version a bit weird, but I understood it as a conscious decision towards "I prefer to let the code run if the `version` string is not properly defined". I prefer the new version though :-).

**Review by asamuzaK — APPROVED** [review]

**Comment by asamuzaK** [comment]
> can you please send it to me in an email so I can setup everything the way you want?

I'll upload it directly. Will that be OK?

> I changed that but I'm not sure it helps code reading. Now, the variable is called node and the reader has no clue that it is a version number.

Yeah, your right, it should be something like `nodeVersion`.
I also use eslint `no-magic-number` rule, I'll fix them after merging this.

Thanks.

**Pull request merged**
